services:
  db:
    restart: unless-stopped
    image: docker.io/postgres
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5432:5432

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    ports: 
      - 8080:8080
    depends_on:
      db:
        condition: service_started
        restart: true
